openapi: 3.0.3
info:
  title: Postcode Sectors API
  description: API endpoints for postcode sector territory management
  version: 1.0.0

servers:
  - url: /api/admin
    description: Admin API endpoints

paths:
  /sectors/list:
    get:
      summary: List sectors by district
      description: Fetch all postcode sectors within a district for drill-down display
      operationId: listSectors
      tags:
        - Sectors
      parameters:
        - name: district
          in: query
          required: true
          description: District code to fetch sectors for (e.g., "TA1", "BS10")
          schema:
            type: string
            pattern: '^[A-Z]{1,2}\d{1,2}$'
            example: "TA1"
      responses:
        '200':
          description: Sectors retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sectors:
                    type: array
                    items:
                      $ref: '#/components/schemas/Sector'
                  district:
                    type: string
                    description: The district code queried
        '400':
          description: Invalid district code format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '404':
          description: District not found or no sectors available

  /sectors/{code}/count:
    get:
      summary: Get property count for sector
      description: Fetch residential property count for a specific sector
      operationId: getSectorPropertyCount
      tags:
        - Sectors
      parameters:
        - name: code
          in: path
          required: true
          description: Sector code (e.g., "TA1 1", "BS10 5")
          schema:
            type: string
            pattern: '^[A-Z]{1,2}\d{1,2}\s\d$'
            example: "TA1 1"
      responses:
        '200':
          description: Property count retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: Number of residential properties
                  cached:
                    type: boolean
                    description: Whether result was from cache
                  sector:
                    type: string
                    description: The sector code queried
        '401':
          description: Unauthorized
        '404':
          description: Sector not found

  /territories:
    post:
      summary: Create territory assignment
      description: Assign agent to district or sectors (extended to support sectors)
      operationId: createTerritory
      tags:
        - Territories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TerritoryAssignment'
      responses:
        '201':
          description: Territory assigned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  assignments:
                    type: array
                    items:
                      $ref: '#/components/schemas/AssignmentResult'
        '400':
          description: Invalid request
        '401':
          description: Unauthorized
        '409':
          description: Conflict - territory already assigned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictError'

  /territories/check-conflicts:
    post:
      summary: Check for assignment conflicts
      description: Preview conflicts before creating assignment
      operationId: checkConflicts
      tags:
        - Territories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TerritoryAssignment'
      responses:
        '200':
          description: Conflict check result
          content:
            application/json:
              schema:
                type: object
                properties:
                  hasConflicts:
                    type: boolean
                  conflicts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Conflict'

components:
  schemas:
    Sector:
      type: object
      properties:
        code:
          type: string
          description: Sector code
          example: "TA1 1"
        district_code:
          type: string
          description: Parent district code
          example: "TA1"
        area_km2:
          type: number
          nullable: true
          description: Area in square kilometers
        boundary:
          type: object
          description: GeoJSON Polygon geometry
          properties:
            type:
              type: string
              enum: [Polygon]
            coordinates:
              type: array
        center_point:
          type: object
          nullable: true
          description: GeoJSON Point for label placement
        assigned_agent:
          type: object
          nullable: true
          description: Agent assigned to this sector (if any)
          properties:
            id:
              type: string
              format: uuid
            subdomain:
              type: string

    TerritoryAssignment:
      type: object
      required:
        - agent_id
        - postcode_code
      properties:
        agent_id:
          type: string
          format: uuid
          description: Agent to assign territory to
        postcode_code:
          type: string
          description: District code
          example: "TA1"
        sector_codes:
          type: array
          items:
            type: string
          nullable: true
          description: Specific sectors to assign (null/empty = full district)
          example: ["TA1 1", "TA1 2", "TA1 3"]

    AssignmentResult:
      type: object
      properties:
        postcode_code:
          type: string
        sector_code:
          type: string
          nullable: true
        assigned_at:
          type: string
          format: date-time

    Conflict:
      type: object
      properties:
        type:
          type: string
          enum: [district_assigned, sector_assigned]
        code:
          type: string
          description: The conflicting postcode/sector code
        agent:
          type: object
          properties:
            id:
              type: string
              format: uuid
            subdomain:
              type: string

    ConflictError:
      type: object
      properties:
        error:
          type: string
          example: "Territory assignment conflict"
        conflicts:
          type: array
          items:
            $ref: '#/components/schemas/Conflict'

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
