-- UK Postcodes Batch Import Script
-- This file will be generated by combining all batch files

-- Run this to generate the complete import file:
-- cd /Users/dan/Documents/Websites/Nest Associates/Project Nest/Nest
-- cat postcode_batches/*.sql > import_all_postcodes_final.sql

-- Then import via Supabase Dashboard SQL Editor or psql:
-- psql "YOUR_DATABASE_URL" -f import_all_postcodes_final.sql

-- Verify after import:
-- SELECT COUNT(*) FROM postcodes;
